// Code generated by capnpc-go. DO NOT EDIT.

package types

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	strconv "strconv"
)

// Represents a generic message on the horizontalApi. Messagetype and length is done by capnproto somehow. empty might be removed in the future (union with only one member is not supported)
type Message capnp.Struct
type Message_body Message
type Message_body_Which uint16

const (
	Message_body_Which_push  Message_body_Which = 0
	Message_body_Which_empty Message_body_Which = 1
)

func (w Message_body_Which) String() string {
	const s = "pushempty"
	switch w {
	case Message_body_Which_push:
		return s[0:4]
	case Message_body_Which_empty:
		return s[4:9]

	}
	return "Message_body_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// Message_TypeID is the unique identifier for the type Message.
const Message_TypeID = 0xa5588519d0dba97f

func NewMessage(s *capnp.Segment) (Message, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Message(st), err
}

func NewRootMessage(s *capnp.Segment) (Message, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Message(st), err
}

func ReadRootMessage(msg *capnp.Message) (Message, error) {
	root, err := msg.Root()
	return Message(root.Struct()), err
}

func (s Message) String() string {
	str, _ := text.Marshal(0xa5588519d0dba97f, capnp.Struct(s))
	return str
}

func (s Message) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Message) DecodeFromPtr(p capnp.Ptr) Message {
	return Message(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Message) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Message) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Message) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Message) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Message) Body() Message_body { return Message_body(s) }

func (s Message_body) Which() Message_body_Which {
	return Message_body_Which(capnp.Struct(s).Uint16(0))
}
func (s Message_body) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Message_body) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Message_body) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Message_body) Push() (PushMsg, error) {
	if capnp.Struct(s).Uint16(0) != 0 {
		panic("Which() != push")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return PushMsg(p.Struct()), err
}

func (s Message_body) HasPush() bool {
	if capnp.Struct(s).Uint16(0) != 0 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_body) SetPush(v PushMsg) error {
	capnp.Struct(s).SetUint16(0, 0)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewPush sets the push field to a newly
// allocated PushMsg struct, preferring placement in s's segment.
func (s Message_body) NewPush() (PushMsg, error) {
	capnp.Struct(s).SetUint16(0, 0)
	ss, err := NewPushMsg(capnp.Struct(s).Segment())
	if err != nil {
		return PushMsg{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Message_body) SetEmpty() {
	capnp.Struct(s).SetUint16(0, 1)

}

// Message_List is a list of Message.
type Message_List = capnp.StructList[Message]

// NewMessage creates a new list of Message.
func NewMessage_List(s *capnp.Segment, sz int32) (Message_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[Message](l), err
}

// Message_Future is a wrapper for a Message promised by a client call.
type Message_Future struct{ *capnp.Future }

func (f Message_Future) Struct() (Message, error) {
	p, err := f.Future.Ptr()
	return Message(p.Struct()), err
}
func (p Message_Future) Body() Message_body_Future { return Message_body_Future{p.Future} }

// Message_body_Future is a wrapper for a Message_body promised by a client call.
type Message_body_Future struct{ *capnp.Future }

func (f Message_body_Future) Struct() (Message_body, error) {
	p, err := f.Future.Ptr()
	return Message_body(p.Struct()), err
}
func (p Message_body_Future) Push() PushMsg_Future {
	return PushMsg_Future{Future: p.Future.Field(0, nil)}
}

const schema_d06424cd5634d6a3 = "x\xda\x84\x93O\x88\x1cE\x14\xc6\xdf\xab\x9e\xdd\xd6\xb0" +
	"\xc3n\xd3\xbb\x12!\xd0\xcfe\x05w5kb\xbc\x18" +
	"\x84\x18\xf5\xa0\x87\x85T6\x91E]\xb1f\xbaf\xba" +
	"\xa0\xbb\xab\xe8\xaa\xce\xd2^B\x04/\x1e\xf5\xe2M\xf1" +
	"\xcf!\xa0\xe0UD\x0f\x82\x17%\x90\x83\xe6\xa0\x08\xae" +
	"\x17\x83\x07\x0f\x1e\x05-\xe9\x99\x9eDdX\x8f\xdd\xaf" +
	"\xfa\xfb\xbe\xfa\xbd\xafO\xbd\x8cO\xf5N\xf7\x93\x00\x18" +
	"\xdfXX\xf4W\xaf\xffx\xf3\xfe7\xf6>\x02\xbe\x8a" +
	"\xe8?\xb8\xf5\xf8\x0b76\xd2\x9b\xb0\x80!@\\\xe3" +
	"/\xf15\x0c\xe3k\x98\xc4\x7f\xe19@\x7f\xe6\xd3/" +
	"\xed\xedo\x1f\xfc\x0a\xf8\x09\xc4\xbb\x1f_\xc6\x10\x19\xc0" +
	"\x19d\xc7\x100\xbe\x97\x1d\x00\xfa'>;<\xb6\xf7" +
	"\xf0\xfa\x0d\xe0\x11\xa2\xff|\xdd\xff~\xf9\x81\xbd\xdb\x9d" +
	"\xf4\xf7\xec\x9b\xf8\x90\x85\xf1!K\xe2\xb5\xe0Wx\xc6" +
	"\xbb\xc6H\xfbh!\x99\xb5b,\xb7\x87\xc2\x94\xe6\xec" +
	"\x8e\xb46\x14cy\x01\x91\xf7\x90\xf9W\xde~\x97\x7f" +
	"q\xeb\xcd\xaf\x81\xf7\x18\x9e\xcf\x11\x97\x00N\xe3\x0f\x0b" +
	"\xfe\xa24\x95\xb4\xb2\xbc\xcfY\x124\x96\xa5\xac\xd4\x90" +
	"\x0a9\x11#]\x92\xcb$e\xbaR\xaf\xe9\xd2\x89\xfc" +
	"\xbcQ\xdb\xb43\x9d\xb6\xc6$\xca\x94rY\x8e]F" +
	"\xcaR\xaaKI\x83\x86&!*\xed4Y]\xc8L" +
	"\x1fl\x93,\x8ck\xa8P\xe3\xcc\xd1@R%\x0b}" +
	"E\xa6\xa4\xa6\x0e\xa3\xda\xd5\x95\xa4\x87\xeaR\xe9\x92\x0e" +
	"\x94\xcbH\x97yC\xad^!\x8b\x81\xacZ\xf9R;" +
	"\xb2\xb51\xbar2H7\x01x/\xe8\x01\xe0\xbf\xf8" +
	"F\xfd-`\xcb\x03\x9d6w\xc0\x04\xff\x05\xd3>\xb5" +
	"'\x00\xf8=Ao\xc9\xfb\x1e\x02D\x9b[\xd1f\xc2" +
	"/\x05\xc8_e\xd8\xc7\xbf\xfd*\xb6\xaf\xf7\x1f\x8b\xf6" +
	"\x13\xfeN\x80\xfcC\x86\xcb\xa6\xb6\xd9\x1c\xa0'&@" +
	"#\xfc\xd3\xcf\xc81\xd5\xf2|\xe9Bm\xb3\x1d;\xde" +
	"\xa7\xe2\xdct\x00\x80+w7\x0c\x88+\x80\xc9\x84\xcd" +
	"\x1c\xd9G\xba=\xfd\x86\xde\xe4b(3\x9d/\xa6\xb2" +
	"\"\xab\xca\xa1\xa4\xffge\xb4\xb5\xcbj\x90K\x08;" +
	"\x1a\xa6f6\xebPt\xd9\x00\xe6\x97d\xa33\x7f\x1d" +
	"\xef\x94daR\x92\x96\xc1\xd1\x0d\x01\x00\xbe\xd2nf" +
	"\x02V\xacG\"\xe1\xef\x05\xc8?f\x18!N\xb9^" +
	"\x7f1\xfa$\xe1\xdf\x05\xc8\x7ff\x181\xb6\xda\xfe\x08" +
	"\xd1O\x17\xa3\xc3dw\x09\x03\xdc=\x8e\x0c1X\xc5" +
	"\x00 ^\xc3\xa7\xe35Lv\x9fl\x07\xcf!\xc3\xd0" +
	"\xb9|N\xe6S]\xe6-\xe6\x9d*\xe4I\xa7O\x86" +
	"\xb9\xba\"\xcfR\xa6\x0f\xa8\x10eC\xa3\xbar\x99\xac" +
	"(\xd3\xc6\x92\xcdt\x9d\xa7\x93\x1b\xcc.4\x90d*" +
	"m\xc4xY8\x99\x02\xe0\"0\\\x04\xf4cm\xad" +
	"2\x97\x1a\x08\x8c\x9cc}\xbc\xab\xc0\xfb\x13\xd2\xa4G" +
	"\x84\xad\xac\x11M\x1ej\xd1\x0a\x85\xc00\x04\x9cU\xe4" +
	"y\xc0g\x8f\xa8\xd2\x1f^\xa5\xb2tj\xa4\xd8P\xb8" +
	"v\xd3z\xd4\x05MfM\xea\x14\xaf\xb6&Z\xa4G" +
	"\xa4z\xcb\x8bj\xa0\\%*lhz\x1c\xdbL}" +
	"`\xd8\x07\xfc'\x00\x00\xff\xff\x13\xcex\x94"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_d06424cd5634d6a3,
		Nodes: []uint64{
			0xa5588519d0dba97f,
			0xc225cbe873beb033,
			0xcd222b580ae1b939,
		},
		Compressed: true,
	})
}
